server:
  error:
    include-message: ALWAYS
    include-stacktrace: NEVER

springdoc:
  swagger-ui:
    path: '/swagger-ui.html'
  version: 1.0


spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}


security:
  admin:
    login: ${ADMIN_LOGIN}
    password: ${ADMIN_PASSWORD}